# SPDX-License-Identifier: Apache-2.0
"""A fail-closed Hilbert-system proof checker (stdlib only).

Formulas are JSON values: an atom is a string ("p"), an implication is
["->", A, B], a negation is ["not", A]. The system is Łukasiewicz's third
axiomatization of classical propositional logic (see
docs/references/lukasiewicz-axioms.md):

    A1:  φ → (ψ → φ)
    A2:  (φ → (ψ → χ)) → ((φ → ψ) → (φ → χ))
    A3:  (¬φ → ¬ψ) → (ψ → φ)

with modus ponens as the only inference rule. A proof object lists steps;
each must be an instance of an axiom schema or follow by MP from two EARLIER
steps, and the last step must be the declared theorem. Anything else raises
ProofError — a proof checker that guesses is worse than none.

This is the point of the example: the committed derivation is the evidence
artifact, and `vericlaim reproduce` re-runs this checker, so "the theorem is
proved" is a claim regenerated from the proof itself on every verification.
The same shape plugs in Lean or Coq: `reproduce` runs the external checker
instead of this one.
"""
from __future__ import annotations

import json
from pathlib import Path

# Metavariables in axiom schemas are ints; anything else must match literally.
_PH, _PS, _CH = 0, 1, 2
AXIOMS: dict[str, list | str] = {
    "A1": ["->", _PH, ["->", _PS, _PH]],
    "A2": ["->", ["->", _PH, ["->", _PS, _CH]],
                 ["->", ["->", _PH, _PS], ["->", _PH, _CH]]],
    "A3": ["->", ["->", ["not", _PH], ["not", _PS]], ["->", _PS, _PH]],
}


class ProofError(ValueError):
    """The proof object does not verify. Fail closed: no report is produced."""


def _match(schema, formula, subst: dict) -> bool:
    """Match *formula* against an axiom *schema*, accumulating metavariable
    bindings in *subst*. A metavariable must bind consistently everywhere."""
    if isinstance(schema, int):
        if schema in subst:
            return subst[schema] == formula
        subst[schema] = formula
        return True
    if isinstance(schema, str):
        return schema == formula
    return (isinstance(formula, list) and len(schema) == len(formula)
            and schema[0] == formula[0]
            and all(_match(s, f, subst) for s, f in zip(schema[1:], formula[1:])))


def _is_axiom_instance(name: str, formula) -> bool:
    schema = AXIOMS.get(name)
    return schema is not None and _match(schema, formula, {})


# claim:CLAIM-THM-001 steps_verified
# The committed derivation of p -> p verifies in 5 steps under this checker;
# the verdict is the evidence artifact, regenerated by evidence.py.
def verify_proof(proof: dict) -> dict:
    """Verify a proof object; return a report or raise ProofError."""
    theorem = proof.get("theorem")
    steps = proof.get("steps")
    if theorem is None or not isinstance(steps, list) or not steps:
        raise ProofError("proof must declare a 'theorem' and non-empty 'steps'")
    derived: list = []
    for n, step in enumerate(steps, 1):
        if not isinstance(step, dict) or "formula" not in step:
            raise ProofError(f"step {n}: not a map with a 'formula'")
        formula, rule = step["formula"], step.get("rule")
        if rule in AXIOMS:
            if not _is_axiom_instance(rule, formula):
                raise ProofError(f"step {n}: formula is not an instance of {rule}")
        elif rule == "MP":
            refs = step.get("from")
            if (not isinstance(refs, list) or len(refs) != 2
                    or not all(isinstance(r, int) and 1 <= r < n for r in refs)):
                raise ProofError(
                    f"step {n}: MP must cite two earlier steps (1-indexed)")
            minor, major = derived[refs[0] - 1], derived[refs[1] - 1]
            if major != ["->", minor, formula]:
                raise ProofError(
                    f"step {n}: MP premises do not yield this formula "
                    f"(need step {refs[1]} == step {refs[0]} -> step {n})")
        else:
            raise ProofError(f"step {n}: unknown rule {rule!r}")
        derived.append(formula)
    if derived[-1] != theorem:
        raise ProofError("last step does not equal the declared theorem")
    return {"theorem": theorem, "steps_verified": len(derived), "qed": True}


def check_file(path: str | Path) -> dict:
    return verify_proof(json.loads(Path(path).read_text(encoding="utf-8")))
