# SPDX-License-Identifier: Apache-2.0
"""Build claimlib's hash-locked literature layer and bind it to the modules.

Reads claimlib/literature/SOURCES.py, writes one hash-locked JSON per work
(literature/<id>.json with a summary_sha256), an INDEX.json, and a BIBLIOGRAPHY.md,
and validates that every ``references`` id used by a module in MODULES.py resolves
to a real literature entry. This is the citation half of Claim-Oriented
Programming: literature that is committed, integrity-checked, and bound to code.

    python claimlib/build_literature.py     # regenerate + validate
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "literature"))

from SOURCES import SOURCES  # noqa: E402
from MODULES import MODULES  # noqa: E402

LIT_DIR = HERE / "literature"
REQUIRED = ("id", "title", "authors", "publisher", "year", "kind", "identifier", "url", "summary")
KIND_LABEL = {"rfc": "RFC", "standard": "Standard", "paper": "Paper",
              "framework": "Framework", "regulation": "Regulation",
              "book": "Book", "specification": "Specification"}


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _write_lf(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def entry_record(src: dict) -> dict:
    for field in REQUIRED:
        if field not in src:
            raise SystemExit(f"[lit] source {src.get('id')!r} missing field {field!r}")
    record = {k: src[k] for k in REQUIRED}
    record["summary_sha256"] = _sha256(src["summary"])
    record["schema"] = "claimlib_literature_v1"
    return record


def validate_references(index: dict) -> list[str]:
    """Every MODULES `references` id must resolve to a literature entry."""
    problems = []
    for mod in MODULES:
        for ref in mod.get("references", []):
            if ref not in index:
                problems.append(f"{mod['name']} cites unknown literature id {ref!r}")
    return problems


def bibliography(records: list[dict], cited_by: dict) -> str:
    lines = ["# claimlib bibliography",
             "",
             "*Generated by `claimlib/build_literature.py`. Each entry's `summary` is "
             "hash-locked (`summary_sha256`) and re-verified by "
             "`claimlib/tests/test_literature.py`; every module reference resolves here.*",
             "",
             f"{len(records)} works, cited by {sum(1 for m in MODULES if m.get('references'))} "
             f"of {len(MODULES)} modules.",
             ""]
    for rec in sorted(records, key=lambda r: r["id"]):
        kind = KIND_LABEL.get(rec["kind"], rec["kind"])
        authors = ", ".join(rec["authors"])
        lines.append(f"### {rec['identifier']} — {rec['title']}")
        lines.append("")
        lines.append(f"*{kind}. {authors}. {rec['publisher']}, {rec['year']}. "
                     f"[{rec['url']}]({rec['url']})*")
        lines.append("")
        lines.append(rec["summary"])
        cites = cited_by.get(rec["id"], [])
        if cites:
            lines.append("")
            lines.append("Cited by: " + ", ".join(f"`{c}`" for c in sorted(cites)) + ".")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    LIT_DIR.mkdir(exist_ok=True)
    ids = [s["id"] for s in SOURCES]
    if len(ids) != len(set(ids)):
        raise SystemExit("[lit] duplicate literature id")

    records = []
    index = {}
    for src in SOURCES:
        rec = entry_record(src)
        _write_lf(LIT_DIR / f"{rec['id']}.json", json.dumps(rec, indent=2, sort_keys=True) + "\n")
        records.append(rec)
        index[rec["id"]] = {"identifier": rec["identifier"], "title": rec["title"],
                            "url": rec["url"], "summary_sha256": rec["summary_sha256"]}

    problems = validate_references(index)
    if problems:
        raise SystemExit("[lit] unresolved references:\n  " + "\n  ".join(problems))

    cited_by: dict[str, list[str]] = {}
    for mod in MODULES:
        for ref in mod.get("references", []):
            cited_by.setdefault(ref, []).append(mod["name"])

    _write_lf(LIT_DIR / "INDEX.json", json.dumps(index, indent=2, sort_keys=True) + "\n")
    _write_lf(LIT_DIR / "BIBLIOGRAPHY.md", bibliography(records, cited_by))
    n_cites = sum(len(m.get("references", [])) for m in MODULES)
    print(f"literature: {len(records)} works, {n_cites} citations from "
          f"{sum(1 for m in MODULES if m.get('references'))} modules; references resolve")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
