# SPDX-License-Identifier: Apache-2.0
"""Generate a self-contained Cloudflare Worker that serves the claimlib registry.

Reads MODULES.py, bundles/INDEX.json and each module's evidence artifact (for the
bound metric value), then emits a dependency-free ES-module Worker
(registry_worker.js) that serves the whole claim registry as a live API:

    GET /            -> HTML index (claims grouped by subject area)
    GET /claims      -> JSON array of every claim
    GET /claims/<id> -> a single claim
    GET /health      -> {"ok": true, "claims": N}

The data is baked in at generate time (no D1/Vectorize/R2 bindings needed), so it
deploys with a single Workers API upload. Regenerate: python claimlib/registry_worker.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from MODULES import MODULES  # noqa: E402

_SUBDIR = {"python": "modules", "typescript": "ts", "react": "react"}


def collect() -> list[dict]:
    index = json.loads((HERE / "bundles" / "INDEX.json").read_text(encoding="utf-8"))
    claims = []
    for mod in MODULES:
        lang = mod.get("lang", "python")
        art = HERE / _SUBDIR[lang] / mod["name"] / "artifacts" / mod["artifact"]
        metrics = json.loads(art.read_text(encoding="utf-8"))
        bound = metrics[mod["bind_field"]]
        claims.append({
            "id": mod["claim_id"],
            "name": mod["name"],
            "title": mod["title"],
            "area": mod["area"],
            "lang": lang,
            "evidence_level": mod["evidence_level"],
            "bind_field": mod["bind_field"],
            "bound_value": bound,
            "statement": " ".join(mod["statement"].split()),
            "caveat": " ".join(mod["caveat"].split()),
            "bundle_id": index.get(mod["name"], ""),
            "references": mod.get("references", []),
            "metrics": {k: metrics[k] for k in mod["register_metrics"]},
        })
    claims.sort(key=lambda c: (c["area"], c["name"]))
    return claims


WORKER_TEMPLATE = """\
// GENERATED by claimlib/registry_worker.py -- do not hand-edit.
// A dependency-free Cloudflare Worker serving the VeriClaim claimlib registry:
// every reusable, claim-bound code artifact, with its bound evidence value.
const CLAIMS = %CLAIMS%;
const BUILT = { generated_from: "vericlaim/claimlib", schema: "claimlib_registry_v1" };

const j = (obj, status = 200) => new Response(JSON.stringify(obj, null, 2), {
  status,
  headers: { "content-type": "application/json; charset=utf-8",
             "access-control-allow-origin": "*",
             "cache-control": "public, max-age=300" },
});

const esc = (s) => String(s).replace(/[&<>"]/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

function page() {
  const byArea = {};
  for (const c of CLAIMS) (byArea[c.area] ||= []).push(c);
  let rows = "";
  for (const area of Object.keys(byArea).sort()) {
    rows += `<tr class="area"><td colspan="5">${esc(area)}</td></tr>`;
    for (const c of byArea[area]) {
      rows += `<tr><td><code>${esc(c.name)}</code></td>`
        + `<td>${esc(c.title)}</td>`
        + `<td>${esc(c.lang)}</td>`
        + `<td>${esc(c.evidence_level)}</td>`
        + `<td><code>${esc(c.bind_field)}</code> = <b>${esc(c.bound_value)}</b></td></tr>`;
    }
  }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VeriClaim claimlib registry</title>
<style>
:root{color-scheme:light dark}
body{font:15px/1.5 system-ui,sans-serif;max-width:1000px;margin:2rem auto;padding:0 1rem}
h1{font-size:1.5rem;margin-bottom:.2rem} p.sub{color:#888;margin-top:0}
table{border-collapse:collapse;width:100%;font-size:14px}
td{padding:.4rem .6rem;border-bottom:1px solid #8883;vertical-align:top}
tr.area td{background:#8882;font-weight:600;padding-top:.8rem}
code{font-family:ui-monospace,monospace} a{color:#3b82f6}
</style></head><body>
<h1>VeriClaim &mdash; claimlib registry</h1>
<p class="sub">${CLAIMS.length} pre-verified, vendorable code artifacts. Each row's
key property is a claim backed by committed evidence. API:
<a href="/claims">/claims</a> &middot; <code>/claims/&lt;id&gt;</code> &middot;
<a href="/health">/health</a>.</p>
<table><tbody>${rows}</tbody></table>
</body></html>`;
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    const path = url.pathname.replace(/\\/$/, "") || "/";
    if (path === "/") return new Response(page(), {
      headers: { "content-type": "text/html; charset=utf-8",
                 "cache-control": "public, max-age=300" } });
    if (path === "/health") return j({ ok: true, claims: CLAIMS.length, ...BUILT });
    if (path === "/claims") return j({ count: CLAIMS.length, claims: CLAIMS });
    if (path.startsWith("/claims/")) {
      const id = decodeURIComponent(path.slice("/claims/".length));
      const hit = CLAIMS.find((c) => c.id === id || c.name === id);
      return hit ? j(hit) : j({ error: "not found", id }, 404);
    }
    return j({ error: "not found", path }, 404);
  },
};
"""


def main() -> int:
    claims = collect()
    (HERE / "registry.json").write_text(
        json.dumps({"count": len(claims), "claims": claims}, indent=2) + "\n",
        encoding="utf-8", newline="\n")
    worker = WORKER_TEMPLATE.replace("%CLAIMS%", json.dumps(claims, ensure_ascii=False))
    (HERE / "registry_worker.js").write_text(worker, encoding="utf-8", newline="\n")
    print(f"generated registry_worker.js + registry.json ({len(claims)} claims)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
