# SPDX-License-Identifier: Apache-2.0
"""The print figures are GENERATED by tools/make_figures.py as deterministic SVG.
This test regenerates them in memory and asserts they match what is committed (so
an edit to the generator that is not re-run fails CI), that every figure the print
editions reference actually exists, and that each SVG is well-formed XML."""
from __future__ import annotations

import importlib.util
import re
import xml.dom.minidom as minidom
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "make_figures", ROOT / "tools" / "make_figures.py")
mf = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mf)

PRINT = ROOT / "docs" / "governance" / "print"


def test_figures_match_committed():
    for lang, strings in mf.STR.items():
        for name, fn in mf.FIGURES.items():
            committed = (mf.OUT / lang / name).read_text(encoding="utf-8")
            assert fn(strings) == committed, (
                f"figures/{lang}/{name} is stale — re-run tools/make_figures.py")


def test_every_referenced_figure_exists():
    referenced = 0
    for md in PRINT.glob("*.md"):
        for _alt, path in re.findall(r"!\[([^\]]*)\]\(([^)]+)\)",
                                     md.read_text(encoding="utf-8")):
            referenced += 1
            assert (PRINT / path).exists(), f"{md.name} references missing {path}"
    assert referenced >= 10  # 2 covers + 3 interior, x2 languages


def test_all_figures_are_well_formed_svg():
    svgs = list(mf.OUT.rglob("*.svg"))
    assert len(svgs) == 10
    for p in svgs:
        minidom.parseString(p.read_text(encoding="utf-8"))  # raises on malformed
