# SPDX-License-Identifier: Apache-2.0
"""SLSA v1.1 Build-track levels + cumulative level assessment — reusable,
claim-bound.

A pre-verified claimlib code artifact for AI assurance and supply-chain
security. SLSA (Supply-chain Levels for Software Artifacts, OpenSSF)
grades how trustworthy an artifact's build is. v1.1 defines a single
track — Build — with CUMULATIVE levels (each includes everything below):

    Build L0: No guarantees        (no requirements — the lack of SLSA)
    Build L1: Provenance exists    (provenance showing how it was built)
    Build L2: Hosted build platform (signed provenance from a hosted
                                     platform — tampering after the build)
    Build L3: Hardened builds      (hardened, isolated build platform —
                                     tampering during the build)

`assess` computes the achieved level from declared capabilities, fail-
closed: a gap at level n caps the result below n regardless of what is
declared above it — you cannot claim L3 while provenance is unsigned.

A level describes the BUILD's integrity, not the code's quality, and the
declaration is the caller's; verification of provenance is a separate act.
SLSA v1.1 was approved 2025-04-21 and has since been superseded by v1.2
(same Build-track structure). ML supply chains attach model artifacts to
exactly this ladder. The caveat travels with the claim.

Public API
----------
    LEVELS: dict[int, dict]        # 0..3 -> {name, focus, requirement}
    CAPABILITIES: tuple[str, ...]  # provenance_exists, hosted_platform,
                                   #   signed_provenance, hardened_platform
    assess(capabilities: Iterable[str]) -> dict

    >>> assess(["provenance_exists"])["level"]
    1
"""
from __future__ import annotations

from collections.abc import Iterable

LEVELS = {
    0: {"name": "Build L0: No guarantees",
        "focus": "(n/a)",
        "requirement": "none"},
    1: {"name": "Build L1: Provenance exists",
        "focus": "Mistakes, documentation",
        "requirement": "provenance showing how the package was built"},
    2: {"name": "Build L2: Hosted build platform",
        "focus": "Tampering after the build",
        "requirement": "signed provenance, generated by a hosted build "
                       "platform"},
    3: {"name": "Build L3: Hardened builds",
        "focus": "Tampering during the build",
        "requirement": "hardened build platform"},
}

# Capability flags a programme declares; levels consume them cumulatively.
CAPABILITIES = ("provenance_exists", "hosted_platform", "signed_provenance",
                "hardened_platform")

_LEVEL_NEEDS = {
    1: {"provenance_exists"},
    2: {"provenance_exists", "hosted_platform", "signed_provenance"},
    3: {"provenance_exists", "hosted_platform", "signed_provenance",
        "hardened_platform"},
}


class SLSAError(ValueError):
    """Unknown capability flag (fail closed)."""


def assess(capabilities: Iterable[str]) -> dict:
    """The achieved Build level for declared *capabilities* — cumulative,
    fail-closed: the result is the highest n whose FULL requirement set is
    met; anything declared above a gap is ignored."""
    have = set(capabilities)
    unknown = sorted(have - set(CAPABILITIES))
    if unknown:
        raise SLSAError(f"unknown capability flag(s): {unknown} — expected "
                        f"{CAPABILITIES}")
    level = 0
    for n in (1, 2, 3):
        if _LEVEL_NEEDS[n] <= have:
            level = n
        else:
            break
    missing_next = sorted(_LEVEL_NEEDS[level + 1] - have) \
        if level < 3 else []
    return {
        "level": level,
        "name": LEVELS[level]["name"],
        "missing_for_next": missing_next,
        "declared": sorted(have),
    }
