# SPDX-License-Identifier: Apache-2.0
"""Generate the enterprise domain-knowledge seed workspace.

Emits, under seed/enterprise/:
    artifacts/<domain>.json (+ .provenance.json)   real computed evidence
    claims/register.yaml                            all enterprise claims
    claims/baseline.json                            green from scratch
    docs/<domain>.md                                a primer + bound claims
    vericlaim.toml                                  gate config

Run:  python seed/enterprise/generate.py   then   python -m vericlaim --root seed/enterprise
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

from domains import ALL_DOMAINS  # noqa: E402


def write_lf(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def write_json(path: Path, obj: dict) -> str:
    text = json.dumps(obj, indent=2) + "\n"
    write_lf(path, text)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def git_commit() -> str | None:
    try:
        out = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                             text=True, cwd=REPO_ROOT, check=True)
        return out.stdout.strip() or None
    except (OSError, subprocess.CalledProcessError):
        return None


def write_provenance(artifact: Path, sha: str, commit: str | None, ts: str) -> None:
    record = {
        "schema": "vericlaim_provenance_v2",
        "artifact": artifact.name,
        "artifact_sha256": sha,
        "script": "python3 seed/enterprise/generate.py",
        "git_commit": commit,
        "generated_at": ts,
        "produced_by": "enterprise-seed-generator",
    }
    write_lf(artifact.with_name(artifact.name + ".provenance.json"),
             json.dumps(record, indent=2) + "\n")


CONFIG = """\
# VeriClaim enterprise domain-knowledge seed — isolated stress-test workspace.
# Regenerate: python seed/enterprise/generate.py
[vericlaim]
profile             = "adopt"
register            = "claims/register.yaml"
baseline            = "claims/baseline.json"
doc_globs           = ["docs/*.md"]
required_fields     = ["id", "statement", "evidence_level", "artifact", "caveat"]
evidence_levels     = ["theoretical", "measured", "benchmarked", "reproduced", "machine_checked", "externally_validated"]
require_provenance  = true
require_git_tracked = false

[vericlaim.stale_strings]
"""

BASELINE = json.dumps({
    "schema": "vericlaim_baseline_v1",
    "description": "Enterprise seed starts green; no grandfathered violations.",
    "known_violations": [],
}, indent=2) + "\n"


def yaml_block(text: str, indent: str) -> str:
    return "\n".join(indent + line for line in text.split("\n"))


def fmt(v) -> str:
    """Stable string form of a metric value for doc binding."""
    if isinstance(v, bool):
        return str(int(v))
    return str(v)


def register_entry(cid: str, claim, artifact_rel: str) -> str:
    metrics_lines = "\n".join(f"      {k}: {fmt(v)}" for k, v in claim.metrics.items())
    return f"""\
  - id: {cid}
    statement: >
{yaml_block(claim.statement, "      ")}
    evidence_level: {claim.level}
    artifact:
      - "{artifact_rel}"
    metrics:
{metrics_lines}
    caveat: >
{yaml_block(claim.caveat, "      ")}
    reproduce: "python3 seed/enterprise/generate.py"
"""


def doc_for_domain(d) -> str:
    parts = [f"# {d.title}\n\n",
             f"*Subject area: {d.area}.*\n\n",
             d.knowledge, "\n\n", "## Claims\n\n"]
    for claim in d.claims:
        cid = f"CLAIM-ENT-{claim.suffix}"
        val = fmt(claim.metrics[claim.bind])
        parts.append(
            f"<!-- claim:{cid} {claim.bind} -->\n"
            f"{claim.statement.strip()} "
            f"(<!-- v:{cid}.{claim.bind} -->**{val}**, key `{claim.bind}`).\n\n")
    return "".join(parts)


def main() -> int:
    (HERE / "artifacts").mkdir(parents=True, exist_ok=True)
    (HERE / "claims").mkdir(parents=True, exist_ok=True)
    (HERE / "docs").mkdir(parents=True, exist_ok=True)
    write_lf(HERE / "vericlaim.toml", CONFIG)
    write_lf(HERE / "claims" / "baseline.json", BASELINE)

    commit = git_commit()
    ts = datetime.now(timezone.utc).isoformat()

    reg = ["---\n",
           "# VeriClaim ENTERPRISE seed register — GENERATED by seed/enterprise/generate.py\n\n",
           'schema_version: "1"\n\n', "claims:\n\n"]
    n_claims = 0
    for make in ALL_DOMAINS:
        d = make()
        artifact = HERE / "artifacts" / d.artifact_name
        art_obj = {"schema": d.artifact["schema"], "domain": d.key,
                   "subject_area": d.area, **d.artifact}
        sha = write_json(artifact, art_obj)
        write_provenance(artifact, sha, commit, ts)
        artifact_rel = f"artifacts/{d.artifact_name}"
        for claim in d.claims:
            reg.append(register_entry(f"CLAIM-ENT-{claim.suffix}", claim, artifact_rel))
            reg.append("\n")
            n_claims += 1
        write_lf(HERE / "docs" / f"{d.key}.md", doc_for_domain(d))

    write_lf(HERE / "claims" / "register.yaml", "".join(reg))
    print(f"seeded {len(ALL_DOMAINS)} enterprise domains, {n_claims} claims, "
          f"{len(ALL_DOMAINS)} knowledge docs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
